@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}

###

http://{{host}}/pets/dog?name=Otis

###

http://{{host}}/pets/dog?name=Otis&format=json

###

http://{{host}}/pets/dog.json?name=Otis

###

http://{{host}}/pets/dog?name=Otis&format=xml

###

http://{{host}}/pets/dog.xml?name=Otis